# Generated by Django 5.0.6 on 2024-08-04 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.IntegerField(verbose_name=11)),
                ('telefone', models.IntegerField(verbose_name=11)),
                ('endereco', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='vendedor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Usuario.usuario')),
                ('descricao', models.CharField(max_length=300)),
            ],
            bases=('Usuario.usuario',),
        ),
    ]
