# Generated by Django 5.0.7 on 2024-08-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
