# Generated by Django 5.0.7 on 2024-08-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProd', models.CharField(max_length=200)),
                ('tipoProd', models.CharField(max_length=200)),
                ('origemProd', models.CharField(max_length=200)),
                ('quantidadeProd', models.IntegerField()),
            ],
        ),
    ]
